# Site settings
title: "CSC2019 - Introduction to Machine Learning"
email: informationcake.com
description: "CERN School of Computing 2019: Introduction to Machine Learning."
baseurl: ""
url: "http://as595.github.io"
twitter_username: alexowenclarke
github_username:  informationcake

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

